### ISSUE TITLE
TestlinkAPIClient does not accept optional argument 'transport' for proxy configuration 

### ISSUE THREAD

**Issue by lczub** [lczub/TestLink-API-Python-client#56]
proxy configuration, introduced with #36, only works with api class _TestlinkAPIGeneric_
the api class *TestlinkAPIClient* does not accept optional arguments like _transport_.

```
tl_helper = TestLinkHelper(proxy='PROXY-71')
myTestLink = tl_helper.connect(TestlinkAPIClient)

Traceback (most recent call last):
  File "D:\Projekte\Testlink-Python-API\Issues\20150601_issue55_getProjects\getProjects_from_demo.py", line 42, in <module>
    myTestLink = tl_helper.connect(TestlinkAPIClient)
  File "D:\Projekte\git\TestLink-API-Python-client\src\testlink\testlinkhelper.py", line 143, in connect
    return tl_api_class(self._server_url, self._devkey, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'transport'

```

**Comment by lczub** [comment]
[Travis build](https://travis-ci.org/lczub/TestLink-API-Python-client/builds/65719137) passed for Py27 - Py34, but failed for Py26.
Seams, that the new unit tests *test_connect_with_proxy* needs a special handling for Py26
